import {  Poppins } from "next/font/google";
import "./globals.css";



const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Providers from "./providers";
import Navbar from "./components/Navbar";

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} antialiased bg-gray-50 min-h-screen`}>
        <Providers>
          <Navbar />
          <main className="pt-4">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
